# Bản dịch tiếng Anh: khoá = chuỗi gốc tiếng Việt. Sinh Resources/en.lproj/Localizable.strings:
#   python3 Scripts/en_strings.py
EN = {
'Đang phát từ': 'PLAYING FROM',
'YouTube Music phát và tải trực tiếp, không cần cài gì thêm. yt-dlp (mã nguồn mở, tuỳ chọn) chỉ là dự phòng khi YouTube đổi cách chặn, và dùng để tải link từ trang web khác. ffmpeg (brew install ffmpeg) giúp tệp tải về chuẩn hơn.': 'YouTube Music plays and downloads directly, nothing extra to install. yt-dlp (open source, optional) is only a fallback for when YouTube changes its blocking, and for downloading links from other websites. ffmpeg (brew install ffmpeg) gives cleaner downloaded files.',
'YouTube: không lấy được mã khách.': 'YouTube: couldn’t get a visitor ID.',
'YouTube từ chối phát video này.': 'YouTube refused to play this video.',
'Không tải được bài này.': 'Couldn’t download this song.',
'Máy chủ trả về lỗi %@.': 'The server returned error %@.',
'Trên iPhone/iPad chỉ nhập được link YouTube, YouTube Music và Spotify.': 'On iPhone/iPad, only YouTube, YouTube Music and Spotify links can be imported.',
'Playlist': 'Playlists',
'Xong': 'Done',
'Chào buổi sáng': 'Good morning',
'Chào buổi chiều': 'Good afternoon',
'Chào buổi tối': 'Good evening',
'Bạn muốn nghe gì?': 'What do you want to listen to?',
'Đang tải xuống': 'Downloading',
'Dán link YouTube, YouTube Music hoặc Spotify.': 'Paste a YouTube, YouTube Music or Spotify link.',
'%@ bài hát': '%@ songs',
'Không phát được “%@”. Thử lại sau hoặc chọn bài khác.': 'Couldn’t play “%@”. Try again later or pick another song.',
'Top Hoa Kỳ': 'Top songs USA',
'Kết nối với thiết bị': 'Connect to a device',
'Mở cửa sổ Muzify': 'Open Muzify window',
'Cửa sổ nổi': 'Mini player',
'%@ người hâm mộ': '%@ fans',
'Đọc thêm trên Wikipedia': 'Read more on Wikipedia',
'Đã bỏ qua đoạn không phải nhạc': 'Skipped a non-music section',
'Âm thanh': 'Audio',
'Bộ chỉnh âm (EQ)': 'Equalizer',
'Kiểu': 'Preset',
'Tuỳ chỉnh': 'Custom',
'Áp dụng cho bài trên máy và bài YouTube Music; một số luồng SoundCloud không hỗ trợ.': 'Works for local and YouTube Music songs; some SoundCloud streams aren’t supported.',
'Tự cân âm lượng': 'Normalize volume',
'Bỏ qua đoạn không phải nhạc': 'Skip non-music sections',
'Tự cân âm lượng giúp các bài to nhỏ đều nhau. Đoạn không phải nhạc (intro, đoạn nói trong MV…) lấy từ cộng đồng SponsorBlock.': 'Normalize volume keeps songs at a similar loudness. Non-music sections (intros, talking in music videos…) come from the SponsorBlock community.',
'Hiện mini player trên thanh menu': 'Show mini player in the menu bar',
'Phẳng': 'Flat',
'Tăng bass': 'Bass boost',
'Giảm bass': 'Bass reducer',
'Tăng treble': 'Treble boost',
'Giọng hát': 'Vocal',
'Điện tử': 'Electronic',
'Đêm khuya': 'Late night',
'Không tìm thấy “%@” trên YouTube Music để tải.': 'Couldn’t find “%@” on YouTube Music to download.',
'Top bài hát Việt Nam': 'Top songs Vietnam',
'Bảng xếp hạng Apple Music': 'Apple Music chart',
'Top toàn cầu': 'Top global',
'Bảng xếp hạng Deezer': 'Deezer chart',
' · %@': ' · %@',
'%@ giờ %@ phút': '%@ hr %@ min',
'%@ phút %@ giây': '%@ min %@ sec',
'%@ và những bài tương tự': '%@ and similar songs',
'%@ — %@': '%@ — %@',
'API riêng': 'Custom API',
'Bài hát': 'Songs',
'Bài hát bạn thích sẽ xuất hiện ở đây': 'Songs you like will appear here',
'Bài hát phổ biến': 'Popular songs',
'Bài hát đã thích': 'Liked Songs',
'Bài này là nhạc không lời': 'This song is instrumental',
'Bài này đã có trong thư viện.': 'This song is already in your library.',
'Bài tiếp': 'Next',
'Bài trước': 'Previous',
'Bạn': 'You',
'Bạn muốn phát nội dung gì?': 'What do you want to play?',
'Bật YouTube Music trong Cài đặt để xem gợi ý và bảng xếp hạng.': 'Turn on YouTube Music in Settings to see recommendations and charts.',
'Bật kho nhạc online trong Cài đặt để tìm bài hát, hoặc dán link để tải.': 'Turn on an online catalog in Settings to search for songs, or paste a link to download.',
'Bật lặp lại': 'Enable repeat',
'Bật tiếng': 'Unmute',
'Bắt đầu mix từ bài này': 'Start a mix from this song',
'Bắt đầu từ %@': 'Starting from %@',
'Bỏ theo dõi': 'Unfollow',
'Chuyển tới nghệ sĩ': 'Go to artist',
'Chưa bật': 'Off',
'Chưa nhập Application ID': 'No Application ID entered',
'Chưa phát bài nào': 'Nothing playing yet',
'Chỉ nhạc trên máy': 'Local music only',
'Chữ cái': 'Alphabetical',
'Cài trình phát online (1 lần)': 'Install the online player (one time)',
'Cài đặt': 'Settings',
'Cách lấy Application ID (1 lần, miễn phí):\n1. Vào discord.com/developers/applications → New Application, đặt tên “Muzify” (tên này hiện trên Discord).\n2. Mục Rich Presence → Art Assets: tải ảnh icon lên với tên “logo”.\n3. Copy Application ID ở mục General Information và dán vào ô trên.\nCần mở app Discord trên máy.':
 'How to get an Application ID (one time, free):\n1. Go to discord.com/developers/applications → New Application, name it “Muzify” (this name shows on Discord).\n2. Rich Presence → Art Assets: upload the icon named “logo”.\n3. Copy the Application ID from General Information and paste it above.\nThe Discord app must be running on this Mac.',
'Công cụ': 'Tools',
'Cần cài yt-dlp trước khi tải từ link (Cài đặt → Thư viện).': 'Install yt-dlp before downloading from a link (Settings → Library).',
'Cập nhật yt-dlp lên bản mới nhất': 'Update yt-dlp to the latest version',
'Danh sách chờ': 'Queue',
'Danh sách chờ trống': 'Your queue is empty',
'Duyệt tìm': 'Browse',
'Duyệt tìm tất cả': 'Browse all',
'Dựa trên %@': 'Based on %@',
'GitHub trả về lỗi.': 'GitHub returned an error.',
'Giải nén yt-dlp không thành công.': 'Couldn’t unpack yt-dlp.',
'Giảm âm lượng': 'Volume Down',
'Giới thiệu về nghệ sĩ': 'About the artist',
'Gần đây': 'Recents',
'Gộp mọi nguồn làm một.': 'All sources merged into one.',
'Gợi ý cho bạn': 'Recommended for you',
'Hiện chỉ hỗ trợ link một bài hát Spotify (open.spotify.com/track/…).': 'Only single Spotify track links are supported (open.spotify.com/track/…).',
'Hiện tất cả': 'Show all',
'Hiện “Đang nghe…” trên Discord': 'Show “Listening to…” on Discord',
'Huỷ': 'Cancel',
'Hãy tìm nội dung cho playlist của bạn': 'Let’s find something for your playlist',
'Hãy đảm bảo viết đúng chính tả, hoặc dùng ít từ khoá hơn.': 'Please make sure your words are spelled correctly, or use fewer keywords.',
'Hết danh sách thì tự phát tiếp bài tương tự.': 'When your music ends, keep playing similar songs.',
'Hết danh sách — Muzify sẽ tự phát tiếp bài tương tự.': 'End of queue — Muzify will keep playing similar songs.',
'Kho nhạc': 'Catalog',
'Kho nhạc online lớn.': 'Large online catalog.',
'Kho nhạc trả về lỗi %@.': 'The catalog returned error %@.',
'Khung đang phát': 'Now playing view',
'Không cài được yt-dlp: %@': 'Couldn’t install yt-dlp: %@',
'Không còn bài nào tiếp theo.': 'Nothing up next.',
'Không có (tuỳ chọn)': 'Not installed (optional)',
'Không có bài nào.': 'No songs.',
'Không dùng kho nhạc online.': 'Don’t use online catalogs.',
'Không kết nối được SoundCloud.': 'Couldn’t connect to SoundCloud.',
'Không lấy được bài “%@” từ %@.': 'Couldn’t get “%1$@” from %2$@.',
'Không nhập được %@: %@': 'Couldn’t import %1$@: %2$@',
'Không rõ': 'Unknown',
'Không thấy Discord — hãy mở app Discord': 'Discord not found — open the Discord app',
'Không tên': 'Untitled',
'Không tìm thấy kết quả nào cho “%@”': 'No results found for “%@”',
'Không tìm thấy tệp đã tải.': 'Downloaded file not found.',
'Không tìm được': 'Search failed',
'Không tải được gợi ý. Kiểm tra kết nối mạng.': 'Couldn’t load recommendations. Check your connection.',
'Không tải được lời bài hát': 'Couldn’t load lyrics',
'Không tải được: %@': 'Couldn’t load: %@',
'Không đọc được thông tin bài hát từ Spotify.': 'Couldn’t read the song info from Spotify.',
'Kéo bài hát thả vào playlist ở Thư viện bên trái, hoặc chuột phải vào bài hát → Thêm vào playlist.': 'Drag songs onto a playlist in Your Library, or right-click a song → Add to playlist.',
'Kết quả hàng đầu': 'Top result',
'LRCLIB lỗi %@.': 'LRCLIB error %@.',
'Link không hợp lệ.': 'Invalid link.',
'Làm mới gợi ý': 'Refresh recommendations',
'Lưu': 'Save',
'Lưu bài hát bằng cách nhấn vào biểu tượng ⊕. Bạn cũng có thể dán link vào ô tìm kiếm hoặc kéo thả tệp nhạc vào đây.': 'Save songs by tapping the ⊕ icon. You can also paste a link into the search box or drop music files here.',
'Lưu vào Bài hát đã thích': 'Save to Liked Songs',
'Lưu vào Thư viện': 'Save to Your Library',
'Lặp lại': 'Repeat',
'Lặp lại một bài': 'Repeat one',
'Lỗi': 'Error',
'Lời bài hát': 'Lyrics',
'Lời bài hát do %@ cung cấp': 'Lyrics provided by %@',
'Lời bài hát này chưa được đồng bộ với bài hát.': 'These lyrics aren’t synced to the song yet.',
'Mix dành cho bạn': 'Made for you',
'Mix hàng ngày': 'Daily mixes',
'Mix tương tự': 'Similar mix',
'Mix tự tạo theo nhạc bạn nghe': 'Mixes based on what you listen to',
'Muzify cần công cụ mã nguồn mở yt-dlp (~30 MB) để phát và tải nhạc từ YouTube Music, SoundCloud.': 'Muzify needs the open-source tool yt-dlp (~30 MB) to play and download music from YouTube Music and SoundCloud.',
'Muzify gọi GET tới địa chỉ trên ({query} = từ khoá) và đọc mảng JSON (hoặc {"results": [...]}). Mỗi bài cần: "title", "artist", "url" (link âm thanh mp3/m4a), tuỳ chọn "artwork", "duration" (giây).': 'Muzify sends a GET request to the address above ({query} = search terms) and reads a JSON array (or {"results": [...]}). Each song needs "title", "artist", "url" (mp3/m4a audio link), optionally "artwork" and "duration" (seconds).',
'Máy': 'Local',
'Mới phát hành': 'New releases',
'Mới thêm trước': 'Recently added',
'Mở Discord Developer Portal': 'Open Discord Developer Portal',
'Mở rộng Thư viện': 'Expand Your Library',
'Mở thư mục nhạc trong Finder': 'Show music folder in Finder',
'Mở trên %@': 'Open on %@',
'Ngôn ngữ': 'Language',
'Mở lại Muzify để đổi ngôn ngữ.': 'Reopen Muzify to change the language.',
'Mở lại ngay': 'Reopen now',
'Nghệ sĩ': 'Artists',
'Nghệ sĩ##một người': 'Artist',
'Bài hát##một bài': 'Song',
'Thư viện##nhãn': 'Library',
'Nguồn': 'Source',
'Nguồn nhạc của riêng bạn.': 'Your own music source.',
'Ngày thêm': 'Date added',
'Ngủ ngon': 'Sleep',
'Nhạc': 'Music',
'Nhạc Trịnh': 'Trinh Cong Son',
'Nhạc Việt': 'Vietnamese Music',
'Nhạc phim': 'Soundtracks',
'Nhập tệp nhạc từ máy…': 'Import music files…',
'Nhập tệp nhạc…': 'Import Music Files…',
'Phát': 'Play',
'Phát (Space)': 'Play (Space)',
'Phát / Tạm dừng': 'Play / Pause',
'Phát lại': 'Playback',
'Phát ngẫu nhiên': 'Shuffle',
'Phát nhạc': 'Playback',
'Phát tiếp theo': 'Play next',
'Phổ biến': 'Popular',
'Playlist của tôi #%@': 'My Playlist #%@',
'Playlist mới': 'New Playlist',
'Playlist • %@ bài hát': 'Playlist • %@ songs',
'Quay lại': 'Go back',
'Rap Việt': 'Vietnamese Rap',
'Remix, cover, nhạc độc lập.': 'Remixes, covers, independent music.',
'Rất dễ! Chúng tôi sẽ giúp bạn.': 'It’s easy, we’ll help you.',
'Rất tiếc, chưa có lời cho bài hát này': 'Sorry, there are no lyrics for this song yet',
'Sai lời? Tìm lại': 'Wrong lyrics? Search again',
'Sao chép link bài hát': 'Copy song link',
'SoundCloud cần yt-dlp — vào Cài đặt → Thư viện để cài.': 'SoundCloud needs yt-dlp — install it in Settings → Library.',
'SoundCloud lỗi %@.': 'SoundCloud error %@.',
'SoundCloud từ chối truy cập.': 'SoundCloud denied access.',
'Sắp xếp theo': 'Sort by',
'Sẽ phát tiếp theo': 'Playing next',
'Sửa thông tin bài hát': 'Edit song details',
'Sửa thông tin chi tiết': 'Edit details',
'Sửa tên / nghệ sĩ…': 'Edit title / artist…',
'Theo dõi': 'Follow',
'Theo hệ thống': 'System',
'Thoát toàn màn hình (Esc)': 'Exit full screen (Esc)',
'Thu gọn / mở rộng Thư viện': 'Collapse / Expand Your Library',
'Thu gọn Thư viện': 'Collapse Your Library',
'Thêm bài hát': 'More songs',
'Thêm tên': 'Add a name',
'Thêm vào Muzify': 'Add to Muzify',
'Thêm vào danh sách chờ': 'Add to queue',
'Thêm vào playlist': 'Add to playlist',
'Thích bài đang phát': 'Like Current Song',
'Thích tất cả': 'Like all',
'Thư viện': 'Your Library',
'Thể loại': 'Genre',
'Thịnh hành tại Việt Nam': 'Trending in Vietnam',
'Thời lượng': 'Duration',
'Thứ tự chữ cái': 'Alphabetical',
'Thứ tự tuỳ chỉnh': 'Custom order',
'Thử lại': 'Retry',
'Thử “Sai lời? Tìm lại” với tên chính xác hơn.': 'Try “Wrong lyrics? Search again” with a more exact name.',
'Tiêu đề': 'Title',
'Tiến tới': 'Go forward',
'Tiếp theo': 'Next up',
'Tiếp theo trong danh sách chờ': 'Next in queue',
'Tiếp theo từ: %@': 'Next from: %@',
'Tiệc tùng': 'Party',
'Toàn màn hình': 'Full screen',
'Trang chủ': 'Home',
'Trong Bài hát đã thích': 'In Liked Songs',
'Trạng thái': 'Status',
'Trộn bài': 'Shuffle',
'Tua lùi 10 giây': 'Skip Back 10 Seconds',
'Tua tới 10 giây': 'Skip Forward 10 Seconds',
'Tuyển tập %@': '%@ collection',
'Tuỳ chọn khác cho %@': 'More options for %@',
'Tên': 'Name',
'Tên bài': 'Title',
'Tên bài, ca sĩ…': 'Song, artist…',
'Tìm': 'Search',
'Tìm bài hát': 'Find songs',
'Tìm kiếm': 'Search',
'Tìm kiếm & nghe online': 'Search & stream',
'Tìm kiếm gần đây': 'Recent searches',
'Tìm trong Thư viện': 'Search in Your Library',
'Tìm trong playlist': 'Search in playlist',
'Tìm “%@”': 'Search “%@”',
'Tình yêu': 'Love',
'Tăng âm lượng': 'Volume Up',
'Tạm dừng': 'Pause',
'Tạm dừng (Space)': 'Pause (Space)',
'Tạo': 'Create',
'Tạo playlist': 'Create playlist',
'Tạo playlist hoặc thêm nhạc': 'Create a playlist or add music',
'Tạo playlist mới': 'Create a new playlist',
'Tạo playlist đầu tiên của bạn': 'Create your first playlist',
'Tải bài hát từ link này': 'Download the song from this link',
'Tải bài hát từ link…': 'Download a song from a link…',
'Tải xuống': 'Download',
'Tất cả': 'All',
'Tất cả nguồn': 'All sources',
'Tập luyện': 'Workout',
'Tập trung': 'Focus',
'Tắt lặp lại': 'Disable repeat',
'Tắt tiếng': 'Mute',
'Tệp trên máy': 'Local file',
'Tự động phát': 'Autoplay',
'Xem trước lời bài hát': 'Lyrics preview',
'Xoá': 'Clear',
'Xoá bản tải xuống': 'Remove download',
'Xoá danh sách chờ': 'Clear queue',
'Xoá khỏi Bài hát đã thích': 'Remove from Liked Songs',
'Xoá khỏi Muzify': 'Delete from Muzify',
'Xoá khỏi danh sách chờ': 'Remove from queue',
'Xoá khỏi playlist này': 'Remove from this playlist',
'Xoá playlist': 'Delete playlist',
'YouTube Music · %@': 'YouTube Music · %@',
'của %@': 'by %@',
'yt-dlp lỗi (mã %@).': 'yt-dlp failed (code %@).',
'Đang hiển thị': 'Showing',
'Đang hoàn tất…': 'Finishing…',
'Đang kết nối…': 'Connecting…',
'Đang lấy thông tin…': 'Getting info…',
'Đang phát': 'Now playing',
'Đang theo dõi': 'Following',
'Đang tải xuống %@ bài hát': 'Downloading %@ songs',
'Đang tải xuống “%@”': 'Downloading “%@”',
'Đang tải…': 'Loading…',
'Đi tới': 'Go',
'Đã có': 'Installed',
'Đã kết nối': 'Connected',
'Đã lưu vào Thư viện': 'Saved to Your Library',
'Đã phát gần đây': 'Recently played',
'Đã sao chép link': 'Link copied',
'Đã sẵn sàng': 'Ready',
'Đã thêm %@ bài vào Bài hát đã thích': 'Added %@ songs to Liked Songs',
'Đã thêm vào %@': 'Added to %@',
'Đã thêm vào Bài hát đã thích': 'Added to Liked Songs',
'Đã thêm vào Thư viện': 'Added to Your Library',
'Đã thêm vào danh sách chờ': 'Added to queue',
'Đã tải xuống': 'Downloaded',
'Đã xoá khỏi Bài hát đã thích': 'Removed from Liked Songs',
'Đã xoá khỏi Thư viện': 'Removed from Your Library',
'Đã xoá playlist': 'Playlist deleted',
'Đóng lời bài hát': 'Close lyrics',
'Địa chỉ API riêng cần có {query}, ví dụ https://…/search?q={query}': 'The custom API address needs {query}, e.g. https://…/search?q={query}',
'Địa chỉ tìm kiếm': 'Search URL',
'Định dạng .%@ không phát được. Cài ffmpeg (brew install ffmpeg) để Muzify tự chuyển đổi.': 'The .%@ format can’t be played. Install ffmpeg (brew install ffmpeg) so Muzify can convert it.',
'Đổi tên…': 'Rename…',
'Ẩn bớt': 'Show less',
'Ẩn khung': 'Hide view',
'• %@ bài hát%@': '• %@ songs%@',
'•%@ %@ bài hát': '•%@ %@ songs',
}

if __name__ == "__main__":
    import os
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    def esc(s): return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    lines = ["/* Muzify — English. Sinh tự động từ Scripts/en_strings.py, đừng sửa tay. */", ""]
    lines += [f'"{esc(k)}" = "{esc(v)}";' for k, v in sorted(EN.items())]
    path = os.path.join(root, "Resources", "en.lproj", "Localizable.strings")
    open(path, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print(f"✓ {path} ({len(EN)} chuỗi)")
